//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopaoquan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id_sale { get; set; }
        public Nullable<decimal> price_sale { get; set; }
        public Nullable<int> sale_off { get; set; }
        public string id_product { get; set; }
    
        public virtual product product { get; set; }
    }
}
