//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopaoquan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id_user { get; set; }
        public string email { get; set; }
        public string name_user { get; set; }
        public string phonenumber { get; set; }
        public string pass { get; set; }
        public string roles { get; set; }
        public string name_roles { get; set; }
    }
}
